- README.md
- classes/class-amp-admanager.php
- classes/class-shortcode.php
This PR does following:
* Fix shortcode attributes function.
* Add support for user defined targeting with custom-targeting attribute in [ampad]. 
* Type casting for Domain variable.
* Update Readme
> Add custom targeting support and doc

- README.md
- amp-admanager.php
- classes/class-amp-admanager.php
- classes/class-shortcode.php
Adds support for different network id, to enable ads from other channels.
> Add network id support

- README.md
- amp-admanager.php
- classes/class-amp-admanager.php
1. Add postName and postId targeting variables
2. Rename single post targeting variables -  `postCategories`, `postTags`
> Update targeting variables

- README.md
- amp-admanager.php
- classes/class-amp-admanager.php
- classes/class-shortcode.php
1. PHPCS Fixes - added escaping for ad html.
2. Doc changes.
> PHPCS fixes and doc changes

- classes/class-amp-admanager.php
> Add data-loading-attribute support

- .github/main.workflow
Adds PHPCS inspection for WordPress and WordPress-Core standards
> Add github workflow

- classes/class-amp-admanager.php
> Add function to get output for all 3 ads in single function call

- README.md
Update readme for changes introduced in https://github.com/rtCamp/amp-admanager/pull/38
> Update readme for new function update.

- classes/class-amp-admanager.php
- classes/class-shortcode.php
> Add ad-refresh support

- README.md
- amp-admanager.php
- classes/class-amp-admanager.php
Adds missing single page targeting
> Add single page targeting

- README.md
- template-parts/amp-resources.php
> Add Single Request Architecture(SRA) support

- README.md
- amp-admanager.php
- classes/class-amp-admanager.php
> Add support upto 300px of width for tablet sizes.

- README.md
- classes/class-amp-admanager.php
> Fix tablet ad size limit to 600px of width

- .github/workflows/pull_request.yml
**This is an auto-generated PR.**
Update is required in the PHPCS workflow file, please merge this PR to update it in default branch.
Also, please make chages in other branches to ensure proper working of PHPCS GitHub action.
In case of doubt/issues please ping sys team.
> [Required Update] PHPCS workflow file

- README.md
> Readme: update contributors flow

- phpcs.xml
Add phpcs.xml for PHPCS ruleset
> feature/GH-66 : Add phpcs.xml for PHPCS ruleset

- phpcs.xml
- tests/bootstrap.php
- tests/classes/test-class-admin.php
- tests/classes/test-class-shortcode.php
- tests/helpers/class-utility.php
- Add test case for classes/class-admin.php
- Add test case for classes/class-shortcode.php
[do-not-scan]
Covers point 2 and 4 in https://github.com/rtCamp/amp-admanager/issues/60#issuecomment-577159151
> Add tests for class-admin.php and class-shortcode.php

- .github/workflows/phpcs_on_pull_request.yml
- README.md
Update Readme with Contributing guideline and Add tests folder to skip_folders list
> Update Readme with Contributing guideline and Add tests folder to skip_folders list

- tests/classes/test-class-admin.php
- tests/classes/test-class-amp-admanager.php
- tests/classes/test-class-shortcode.php
- Add a description for test functions
> Add docblock description for test functions

- .github/workflows/pull_request.yml
**This is an auto-generated PR.**
Please make chages in other branches to ensure proper working of GitHub actions.
In case of doubt/issues please ping sys team.
> [Actions Update] Remove Vault dependency from workflows
